name: deploy
run-name: ${{ github.actor }} is deploying main
on:
  push:
    branches:
      - main
runs:
  using: 'node20'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm install

      - name: Deploy
        run: npm run deploy