name: deploy
run-name: ${{ github.actor }} is deploying main
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Authorization - Email
        run: git config user.email "$(git log -n 1 --pretty=format:%ae)"
      
      - name: Authorization - Username
        run: git config user.name "$(git log -n 1 --pretty=format:%an)"

      - name: Debug
        run: git config --list

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.20'

      - name: Install dependencies
        run: npm install --legacy-peer-deps

      - name: Deploy
        run: npm run deploy

    